### ISSUE TITLE
Add configuration file support

### ISSUE THREAD

**Issue by nodece** [casbin/casbin-mesh#39]
### Summary

Currently, the casbin-mesh doesn't support the configuration file, we should support this which is important, I create a draft for this:
```yml
name:

data-dir:

log:
  level: info
  
bind-address:
  - 192.168.1.10:4001
  - 10.168.1.10:4002

advertise-address: 192.168.1.10:8080

endpoint:
  tls:
    enable: false
    ca:
    key:
    cert:
  authorization:
    enable: false
  authentication:
    enable: false
    type: basic
    params:
      username: root
      password: root

raft:
  tls:
    enable: false
    ca:
    key:
    cert:
  snap-threshol: 10
  snap-interval: 10
  leader-lease-timeout: 0
  heart-beat-timeout: 0
  election-timeout: 0
  apply-timeout: 0
  open-timeout: 0
  wait-leader: false
  shutdown-on-remove: false
  compression-size: 10
  compression-batch: 20

pprof:
  enable: false
  cpu-profile:
  mem-profile:
```
